// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/mempool.proto

package common // import "github.com/hyperledger/fabric/protos/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_SUCCESS StatusCode = 0
	StatusCode_FAILED  StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}
var StatusCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mempool_2e278c6f46a0df63, []int{0}
}

type SubmitTxResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SubmitTxResponse) Reset()         { *m = SubmitTxResponse{} }
func (m *SubmitTxResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitTxResponse) ProtoMessage()    {}
func (*SubmitTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mempool_2e278c6f46a0df63, []int{0}
}
func (m *SubmitTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTxResponse.Unmarshal(m, b)
}
func (m *SubmitTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTxResponse.Marshal(b, m, deterministic)
}
func (dst *SubmitTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTxResponse.Merge(dst, src)
}
func (m *SubmitTxResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitTxResponse.Size(m)
}
func (m *SubmitTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTxResponse proto.InternalMessageInfo

func (m *SubmitTxResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

type FetchTxsRequest struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	TxNum                int32    `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTxsRequest) Reset()         { *m = FetchTxsRequest{} }
func (m *FetchTxsRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTxsRequest) ProtoMessage()    {}
func (*FetchTxsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mempool_2e278c6f46a0df63, []int{1}
}
func (m *FetchTxsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTxsRequest.Unmarshal(m, b)
}
func (m *FetchTxsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTxsRequest.Marshal(b, m, deterministic)
}
func (dst *FetchTxsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTxsRequest.Merge(dst, src)
}
func (m *FetchTxsRequest) XXX_Size() int {
	return xxx_messageInfo_FetchTxsRequest.Size(m)
}
func (m *FetchTxsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTxsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTxsRequest proto.InternalMessageInfo

func (m *FetchTxsRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *FetchTxsRequest) GetTxNum() int32 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

type FetchTxsResponse struct {
	TxNum                int32    `protobuf:"varint,1,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	IsEmpty              bool     `protobuf:"varint,2,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTxsResponse) Reset()         { *m = FetchTxsResponse{} }
func (m *FetchTxsResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTxsResponse) ProtoMessage()    {}
func (*FetchTxsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mempool_2e278c6f46a0df63, []int{2}
}
func (m *FetchTxsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTxsResponse.Unmarshal(m, b)
}
func (m *FetchTxsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTxsResponse.Marshal(b, m, deterministic)
}
func (dst *FetchTxsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTxsResponse.Merge(dst, src)
}
func (m *FetchTxsResponse) XXX_Size() int {
	return xxx_messageInfo_FetchTxsResponse.Size(m)
}
func (m *FetchTxsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTxsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTxsResponse proto.InternalMessageInfo

func (m *FetchTxsResponse) GetTxNum() int32 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

func (m *FetchTxsResponse) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

type EndorsedTransaction struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndorsedTransaction) Reset()         { *m = EndorsedTransaction{} }
func (m *EndorsedTransaction) String() string { return proto.CompactTextString(m) }
func (*EndorsedTransaction) ProtoMessage()    {}
func (*EndorsedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_mempool_2e278c6f46a0df63, []int{3}
}
func (m *EndorsedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorsedTransaction.Unmarshal(m, b)
}
func (m *EndorsedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorsedTransaction.Marshal(b, m, deterministic)
}
func (dst *EndorsedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorsedTransaction.Merge(dst, src)
}
func (m *EndorsedTransaction) XXX_Size() int {
	return xxx_messageInfo_EndorsedTransaction.Size(m)
}
func (m *EndorsedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorsedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_EndorsedTransaction proto.InternalMessageInfo

func (m *EndorsedTransaction) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func init() {
	proto.RegisterType((*SubmitTxResponse)(nil), "protos.SubmitTxResponse")
	proto.RegisterType((*FetchTxsRequest)(nil), "protos.FetchTxsRequest")
	proto.RegisterType((*FetchTxsResponse)(nil), "protos.FetchTxsResponse")
	proto.RegisterType((*EndorsedTransaction)(nil), "protos.EndorsedTransaction")
	proto.RegisterEnum("protos.StatusCode", StatusCode_name, StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MempoolClient is the client API for Mempool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MempoolClient interface {
	SubmitTransaction(ctx context.Context, in *EndorsedTransaction, opts ...grpc.CallOption) (*SubmitTxResponse, error)
	FetchTransactions(ctx context.Context, in *FetchTxsRequest, opts ...grpc.CallOption) (*FetchTxsResponse, error)
}

type mempoolClient struct {
	cc *grpc.ClientConn
}

func NewMempoolClient(cc *grpc.ClientConn) MempoolClient {
	return &mempoolClient{cc}
}

func (c *mempoolClient) SubmitTransaction(ctx context.Context, in *EndorsedTransaction, opts ...grpc.CallOption) (*SubmitTxResponse, error) {
	out := new(SubmitTxResponse)
	err := c.cc.Invoke(ctx, "/protos.Mempool/SubmitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mempoolClient) FetchTransactions(ctx context.Context, in *FetchTxsRequest, opts ...grpc.CallOption) (*FetchTxsResponse, error) {
	out := new(FetchTxsResponse)
	err := c.cc.Invoke(ctx, "/protos.Mempool/FetchTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MempoolServer is the server API for Mempool service.
type MempoolServer interface {
	SubmitTransaction(context.Context, *EndorsedTransaction) (*SubmitTxResponse, error)
	FetchTransactions(context.Context, *FetchTxsRequest) (*FetchTxsResponse, error)
}

func RegisterMempoolServer(s *grpc.Server, srv MempoolServer) {
	s.RegisterService(&_Mempool_serviceDesc, srv)
}

func _Mempool_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndorsedTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Mempool/SubmitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServer).SubmitTransaction(ctx, req.(*EndorsedTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mempool_FetchTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServer).FetchTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Mempool/FetchTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServer).FetchTransactions(ctx, req.(*FetchTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mempool_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Mempool",
	HandlerType: (*MempoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _Mempool_SubmitTransaction_Handler,
		},
		{
			MethodName: "FetchTransactions",
			Handler:    _Mempool_FetchTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/mempool.proto",
}

func init() { proto.RegisterFile("common/mempool.proto", fileDescriptor_mempool_2e278c6f46a0df63) }

var fileDescriptor_mempool_2e278c6f46a0df63 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6a, 0xf2, 0x40,
	0x14, 0x86, 0x8d, 0x60, 0xf4, 0x3b, 0x5f, 0xb1, 0x71, 0xfa, 0x67, 0xdb, 0x8d, 0x84, 0x0a, 0x62,
	0x21, 0x01, 0xbb, 0x2f, 0x6d, 0x35, 0xd2, 0x82, 0xed, 0x22, 0xb1, 0x9b, 0x6e, 0x24, 0x3f, 0x53,
	0x0d, 0x38, 0x99, 0x74, 0xce, 0x04, 0xe2, 0xe5, 0xf4, 0x4e, 0x8b, 0x99, 0xd8, 0x88, 0x74, 0x15,
	0x4e, 0x78, 0xde, 0x37, 0x39, 0xcf, 0x0c, 0x9c, 0x86, 0x9c, 0x31, 0x9e, 0xd8, 0x8c, 0xb2, 0x94,
	0xf3, 0xb5, 0x95, 0x0a, 0x2e, 0x39, 0xd1, 0x8b, 0x07, 0x9a, 0xf7, 0x60, 0x78, 0x59, 0xc0, 0x62,
	0x39, 0xcf, 0x5d, 0x8a, 0x29, 0x4f, 0x90, 0x92, 0x21, 0xe8, 0x28, 0x7d, 0x99, 0x61, 0x57, 0xeb,
	0x69, 0x83, 0xf6, 0x88, 0xa8, 0x0c, 0x5a, 0x5e, 0xf1, 0x76, 0xcc, 0x23, 0xea, 0x96, 0x84, 0xf9,
	0x00, 0xc7, 0x53, 0x2a, 0xc3, 0xd5, 0x3c, 0x47, 0x97, 0x7e, 0x65, 0x14, 0x25, 0x39, 0x07, 0x1d,
	0x69, 0x12, 0x51, 0x51, 0xc4, 0xff, 0xb9, 0xe5, 0x44, 0xce, 0x40, 0x97, 0xf9, 0x22, 0xc9, 0x58,
	0xb7, 0xde, 0xd3, 0x06, 0x0d, 0xb7, 0x21, 0xf3, 0xb7, 0x8c, 0x99, 0x13, 0x30, 0xaa, 0x86, 0xf2,
	0x0f, 0x2a, 0x54, 0xdb, 0x43, 0xc9, 0x25, 0xb4, 0x62, 0x5c, 0x50, 0x96, 0xca, 0x4d, 0xd1, 0xd1,
	0x72, 0x9b, 0x31, 0x3a, 0xdb, 0xd1, 0xec, 0xc3, 0x89, 0x93, 0x44, 0x5c, 0x20, 0x8d, 0xe6, 0xc2,
	0x4f, 0xd0, 0x0f, 0x65, 0xcc, 0x13, 0xd2, 0x86, 0xba, 0xcc, 0x8b, 0x92, 0x23, 0xb7, 0x2e, 0xf3,
	0x61, 0x1f, 0xa0, 0x5a, 0x82, 0xfc, 0x87, 0xa6, 0xf7, 0x3e, 0x1e, 0x3b, 0x9e, 0x67, 0xd4, 0x08,
	0x80, 0x3e, 0x7d, 0x7c, 0x99, 0x39, 0x13, 0x43, 0x1b, 0x7d, 0x6b, 0xd0, 0x7c, 0x55, 0xbe, 0xc8,
	0x0c, 0x3a, 0xa5, 0xa1, 0xbd, 0xde, 0xeb, 0x9d, 0x92, 0x3f, 0x3e, 0x7a, 0xd5, 0xfd, 0xf5, 0x75,
	0x60, 0xd6, 0xac, 0x91, 0x67, 0xe8, 0xa8, 0x6d, 0x2b, 0x1e, 0xc9, 0xc5, 0x2e, 0x70, 0xa0, 0xb2,
	0x6a, 0x3a, 0x34, 0x64, 0xd6, 0x9e, 0x3c, 0xb8, 0xe1, 0x62, 0x69, 0xad, 0x36, 0x29, 0x15, 0x6b,
	0x1a, 0x2d, 0xa9, 0xb0, 0x3e, 0xfd, 0x40, 0xc4, 0xe1, 0x2e, 0xa3, 0xce, 0xfd, 0xe3, 0x76, 0x19,
	0xcb, 0x55, 0x16, 0x6c, 0x47, 0x7b, 0x0f, 0xb6, 0x15, 0x6c, 0x2b, 0xd8, 0x56, 0x70, 0xa0, 0xae,
	0xc5, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x14, 0x80, 0xc2, 0x35, 0x02, 0x00, 0x00,
}
